### ISSUE TITLE
PSDs

### ISSUE THREAD

**Issue by Backslashh** [lukevink/hass-config-lajv#11]
Hey Mate,
Love what you have done.
Any chance you can supple the PSD's for the sidebar buttons and person circles?
Trying to keep the same look and feel. :-)

**Comment by BoraSchninsky** [comment]
the same question,,, for me

**Comment by lukevink** [comment]
hey gents - its all in UI Source:

https://github.com/lukevink/hass-config-lajv/blob/master/ui-source/FloorplanExample.psd
