### ISSUE TITLE
Weather Card

### ISSUE THREAD

**Issue by Backslashh** [lukevink/hass-config-lajv#13]
Hey @lukevink ,
What weather card is being used on the weather tab? I know you are using your custom rain forecast card, but I mean for the weather forecast. Your config references that it is in HACS, but I can't seem to find it.

Can you please point me in the right direction?

Thanks.

**Comment by marianbezeg** [comment]
@Backslashh Hi, it should be https://github.com/bramkragten/weather-card

**Comment by Backslashh** [comment]
Yeah cool. 
I grabbed the right one then. 

Thanks mate.
