### ISSUE TITLE
Can be this Lovelace responsive?

### ISSUE THREAD

**Issue by loop2** [lukevink/hass-config-lajv#16]
Can be this Lovelace responsive in order to use it also n a little phone display?
Thanks

**Comment by lukevink** [comment]
The only thing with mobile browsers is the icon sizes. For now I have uploaded my latest code which has a mobile version of lovelace and an updated method for doing the icons, using button-card.

The icons are still manually scaled with transform: 'scale(1.8)' for mobile, so in future I will see if I can just make it responsive for retina screens. I found this easier for myself than trying to handle all other displays etc which I simply can't test myself. On my next update I will try to see if I can make them all just responsive anyway! 

https://github.com/lukevink/hass-config-lajv/blob/master/ui-lovelace_mobile.yaml
