### ISSUE TITLE
mini-graph-card causing errors

### ISSUE THREAD

**Issue by JangoBritt** [lukevink/hass-config-lajv#3]
Hey Luke,

I'm trying to implement this on my own Hassio... obviously have changed a number of the entities to match my own, but am having this problem on the main sidebar:

```
Cannot assign to read only property '0' of object '[object Array]'
color_thresholds:
  - color: '#4dd2ff'
    value: 10
  - color: '#ffa31a'
    value: 15
  - color: '#ff1a1a'
    value: 20
entities:
  - sensor.dark_sky_temperature
icon: 'mdi:home-thermometer-outline'
show:
  icon: true
  legend: false
  name: false
style: |
  :host {
    left: 11.6%;
    top:  92.9%;
    width: 23.5%;
    overflow: hidden;
    height: 15%;
    background: none  !important;
    box-shadow: none !important;
  }
  .header {
    font-size: 1vw;
    position: absolute !important;
    width: 5% !important;

```

**Comment by lukevink** [comment]
Hey there,

Can you check what version of hass you are running? It might be that the mini-graph-card version in my config is old and your hass version is new, in which case first try updating mini-graph-card.

I need to push my latest config where I updated all the versions of those custom cards for the new hass version 0.106 which caused ALOT of changes.

https://community.home-assistant.io/t/cannot-assign-to-read-only-property-0-of-object-object-array/176133/9?u=lukevink

Will push my updated in the next couple of days.

**Comment by JangoBritt** [comment]
ok, great.

I'm on 0.107.6

Updating the mini-graph-card (and clearing the cache) fixed that particular problem, thank you!

**Comment by lukevink** [comment]
Great! Yea there was a whole series of issues updating to that version, will push my new code.
