### ISSUE TITLE
Refresh issues?

### ISSUE THREAD

**Issue by dannymertens** [lukevink/hass-config-lajv#6]
Hi,

I got your config more or less working, but got some strange issues, maybe you can give me an idea what I'm doing wrong here?

- ~I have the same error as reported here: https://github.com/lukevink/hass-config-lajv/issues/5~ Fixed with the help of @brux88

- When I click on a light bulb the light goes on, but when I click again nothing happens?
- When I click on the light then this is not visible in the plan, when I refresh it works

I'm not at developer so probably my stupid mistake but any help is very appreciated to get it working, thanks!

Short video to make the above a little more clear I hope ;-)

https://dmertens.stackstorage.com/s/ujdeR00KjDgArMt

Supervisor: Version | 220
HassOS: Version: | HassOS 3.13
HA: Version | 0.109.3

Thanks!

Kind regards,

Danny

**Comment by brux88** [comment]
yue change 
 ###################   Picture Elements Card    #####################
          type: 'custom:hui-picture-elements-card'        

to

 ###################   Picture Elements Card    #####################
          type: 'picture-element'        


and work

**Comment by dannymertens** [comment]
> you change
> ################### Picture Elements Card #####################
> type: 'custom:hui-picture-elements-card'
> 
> to
> 
> ################### Picture Elements Card #####################
> type: 'picture-element'
> 
> and work

Great, thanks works, but still have the other issues, update floormap, any idea?

- When I click on a light bulb the light goes on, but when I click again nothing happens?
- When I click on the light then this is not visible in the plan, when I refresh and click on another tab and then go back to the floor tab then nothing happens, when I refresh then i works, so seems to be a refresh, timeout issue or something similar.

Thanks!

**Comment by brux88** [comment]
have you tried cleaning the entire cache, or doing control + f5 or on an incognito window, if it always gives you the same problem?

**Comment by dannymertens** [comment]
OK don't know what's wrong with the test config I created from your example, but created everything from scratch for my new dash based on your examples and works fine now!

I want to congratulate you and say thank you for what you created and more how you supported the community with explaining this and adding clear and understandable comments to your config and github page!

Believe me that's not always the case, and i'm very grateful for this!!! because of this it was even for a non developer quite easy to understand and create a very nice dashboard that everybody in my family is loving, even my wife as non techie said Ok I have to say this is quite handy, and believe me that means something :-P

Thank you!!
