### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by roh735** [lukevink/hass-config-lajv#8]
sorry, new in home assistant please let me know ho i can install it? i have Hass installed so i can add scripts from git hub please help me, may be its video how to do it or what i need to do first to get same result?

**Comment by lukevink** [comment]
You will need to copy the files to your home assistant config folder and then edit every entity in my configuration to be your entities. This config is not a simple, easy install - it will require you to create your own home's images and have a good handle on home assistant. 

Unfortunately I do not have the time to post videos and tutorials on this, but the home assistant community is very supportive in helping you figure things out on your own - which will be very rewarding! 

I recommend you start off with a much easier theme, or just with the basic home assistant config. When you start to understand what entities, integrations, YAML etc etc are - then you can start playing with this theme. You will also (for this theme) need to have some knowledge of CSS, photoshop and sweet home 3D.

https://www.youtube.com/watch?v=hFDVB2H6TNo
https://www.youtube.com/watch?v=n5xMtONydEo
